project:
  type: website
  output-dir: docs

website:
  title: "Chloe Robinson â€“ MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
      - text: Labs
        menu:
          - href: Labs/Lab1/Script/assignment1_template.qmd
            text: Lab 1
          - href: Labs/Lab2/Script/assignment2_template.qmd
            text: Lab 2
          - href: Labs/Midterm/model_script.qmd
            text: Midterm Technical Appendix
          - href: Labs/Midterm/midterm_presentation.qmd
            text: Midterm Presentation
          - href: Labs/Lab3/Script/Lab3_new.qmd
            text: Lab 3
          - href: Labs/Lab 5/Script/Indego_Space_Time_Predictions_Assignment.qmd 
            text: Lab 5
            
          
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
